name: Fetch
on:
  schedule:
    # run once a month on the twenty-first day of the month at 00:30 UTC
    - cron: '30 0 21 * *'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Write secrets to file
      run: |
        cat << EOF > ./client_secrets.json
        ${{ secrets.GDRIVE_CLIENT_SECRETS }}
        EOF
        cat << EOF > ./credentials.json
        ${{ secrets.GDRIVE_CREDENTIALS }}
        EOF
        cat << EOF > ./.env
        ${{ secrets.ENV }}
        EOF
        cat << EOF > ./tokens.csv
        ${{ secrets.TOKENS }}
        EOF
      
    - name: Run docker-compose
      uses: hoverkraft-tech/compose-action@v2.0.2
